### ISSUE TITLE
Implementing Resource Owner Password Flow ???

### ISSUE THREAD

**Issue by lapak10** [WP-API/OAuth1#132]
I own site and i created an official android app for the same site... now i want the users to be able to login with simply username and password (no prompting of authorize screen)... i read its in OAuth2 ...but i dont know how to implement it with Oauth1.0a plugin...?? help???

**Comment by matthiasbe** [comment]
@lapak10 I have the same issue, opened a topic in WP REST API support.
https://wordpress.org/support/topic/authenticate-users-with-oauth

**Comment by kosso** [comment]
The WP-API does not use OAuth2 for the reasons [stated here](http://oauth1.wp-api.org/docs/introduction/OAuth-1.html) 

(tldr; OAuth2 *requires* the site running over secure https.  OAuth1.0a does not)

Also on that documentation site you should find some instructions on using OAuth1.0a

**Comment by matthiasbe** [comment]
@kosso Thanks for the reference, do you know a way to authenticate users without redirecting them to an authorizing page ? I can't understand no-one had this issue before ...

**Comment by kosso** [comment]
No. This is primarily how OAuth1 works, so that users of third party apps can be trusted to connect to APIs. The user has to at some point log in to the 'host' (API) site. They will recognise it as their own site, and therefore trust it. Once you have the required oauth token and token secret for the user, you can then use the WP-API via OAuth1. This is often the tricky bit, as you then need to *sign* your requests to the API which many existing libraries can help you with. 

I agree though, that OAuth2 is much, much simpler, as also provides a means for a native app to log in a user without the (so-called) OAuth 'dance'. And since OAuth2 needs SSL https, the requests to the API do not need to be signed, and only need a single Bearer access token to authenticate them with. 

Wordpress *has* to support non-https for now, so OAuth1.0a is the only way to go for now.

**Comment by matthiasbe** [comment]
@kosso Thank you for your fast and precise answer :)
I'm deducing that to get this working I have to use WordPress with SSL (HTTPS), and send request from my App with Basic Authentication. Would this be a solution ?

**Comment by lapak10** [comment]
@kosso i understand why we are using OAuth1.0a (instead of using OAuth2) and it's not something i care of right now..
My concern is , **is there any plugin (or trick )? which i can use in production, to authenticate users of my WP-REST enabled site in my OFFICIAL REST-based mobile application (no third party apps) using only USERNAME and PASSWORD (which they use for my WP site)...without showing them screen to AUTHORIZE (because its OFFICIAL app!!..so have to authorize obviously!)**

Or is there any other (better) way to use in production to authenticate simply by username and password??

**Comment by lapak10** [comment]
@matthiasbe hey mate...did you got any working solution of this issue???? I'm still stuck there 😞

**Comment by matthiasbe** [comment]
@lapak10 Hi again,
In my opinion you have to get SSL/HTTPS on your website to access it from your app.

You cannot pass login/password to your website without having them crypted, else they would be visible by anyone on the network. This is why you need SSL. This is why Oauth uses a redirecting page with a SSL to get the credentials. The get get credentials with a crypted connection and give you a token, and you will be able to use this token without crypted connection.

You have two solutions
* You get SSL for you whole website, then you don't bother with tokens, you just pass your credentials at every request
* You get SSL for only one page (cheaper), then you use this page to exchange credentials and tokens, in order to use your token on every page.

**Comment by joehoyle** [comment]
Closing this out as I think the discussion is done here.

FWIW we don't ever support first-party uath via username / password, to stick to the idea that the user should only ever put their username and password in the wp-login form at their site url.
