### ISSUE TITLE
OAuth noob: why is wordpress showing me my verification token?

### ISSUE THREAD

**Issue by chuckdries** [WP-API/OAuth1#149]
It's showing the user this page 
![Your verification token is xxxx](http://i.imgur.com/vwZuBC8.png)

Shouldn't it redirect and post the token back to the callback url?

**Comment by kadamwhite** [comment]
I think there's an incorrect conditional in [class-wp-rest-oauth1-ui.php](https://github.com/WP-API/OAuth1/blob/master/lib/class-wp-rest-oauth1-ui.php#L138-L150), where it says
```php
		if ( ! empty( $this->token['callback'] ) && $this->token['callback'] === 'oob' ) {
			return apply_filters( 'json_oauth1_handle_callback', null, $this->token );
		}
		if ( empty( $this->token['callback'] ) ) {
			// No callback registered, display verification code to the user
			login_header( __( 'Access Token', 'rest_oauth1' ) );
			echo '<p>' . sprintf( __( 'Your verification token is <code>%s</code>', 'rest_oauth1' ), $verifier ) . '</p>';
			login_footer();
			return null;
		}
```
If I'm reading this right, it will always redirect if the callback IS "oob" (out of band), but will always show the credentials INSTEAD of redirecting otherwise. This is also preventing me from using the out of band flow without a modified version of the plugin.

**Comment by rmccue** [comment]
@kadamwhite You're right. If your callback is set to oob, it should display the code, rather than returning I think. Something like `empty( $this->token['callback'] ) || $this->token['callback'] === 'oob'`

I seem to recall this working in the past, so wondering if something changed.

**Comment by kadamwhite** [comment]
Hmm. I think my reading is incorrect; the short-circuit for oob should not prevent the proper redirect logic further down. But if callback is oob, I would still expect to get the same results as in the image in this issue, rather than being passed off to redirect.

@chuckdries What do you have set for the callback in your registered application?

**Comment by kadamwhite** [comment]
Whoops, missed @rmccue's most recent comment! I tried to blame through the file and couldn't see anything overt that would have introduced it, so, :shrug:. But I'll submit a PR for the provisional solution, since that's how I got it working locally.
