### ISSUE TITLE
Unable to get the key and secret 

### ISSUE THREAD

**Issue by crisanders** [WP-API/OAuth1#39]
Installed the WP API plugin and then the OAuth1 as well, but every time I go my dedicated server and try to run this

```bash
$ wp oauth1 add

It gives an error and nothing is returned. 

root@server1 [/home/site/www]# wp
-bash: wp: command not found

Any idea what I'm doing wrong? I can't figure it out.

Thank you

**Comment by BenjaminBarnett** [comment]
@romuloctba, any chance you can re-post the plugin .rar? The link you posted previously is offline atm. Thanks in advance,   :Benjamin Barnett

**Comment by romuloctba** [comment]
Here you go, pal... But i believe someone released a better plugin, I'm not
sure where to find it, thou....
Anyway, maybe it can at least inspire you

https://gist.github.com/romuloctba/b973ff6bf87452e72f83

The .rar had this file inside a folder create-key/ and also a png located
in create-key/images/b_status.png wich was a menu icon... so
-create-key
-----/create_key.php
-----/images
-------------/b_status.png

2015-03-24 14:51 GMT-03:00 BenjaminBarnett <notifications@github.com>:

**Comment by BenjaminBarnett** [comment]
Thanks, dude, you're an absolute life-saver. I just could NOT get wp-cli.phar to build on my server, it was driving me NUTS. A thousand thanks.  :Benjamin Barnett

**Comment by wesleyxiao** [comment]
http://192.168.1.103/wordpress/oauth1/request?oauth_consumer_key=7hSFwPVlnu80&oauth_nonce=NTfUDG9WQyz&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1435806467&oauth_version=1.0

i am put this link on browser, and show error Missing OAuth parameter oauth_signature, can anyone help please, i am noob with oauth, try to figure it out almost 3 days

**Comment by wesleyxiao** [comment]
ok i am add oauth_signature to the link
http://192.168.1.103/wordpress/oauth1/request?oauth_consumer_key=7hSFwPVlnu80&oauth_nonce=NTfUDG9WQyz&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1435806467&oauth_version=1.0&oauth_signature=iNc86VsVHNxdlScUM2pUFJYvMwI=

it show error OAuth signature does not match

no idea why

**Comment by wesleyxiao** [comment]
here i try so far

i use  romuloctba plugin to create key and secret (thanks  romuloctba )

and then i add the patch on authorization_oauth1.php

$home_url_path = parse_url(get_home_url (null,''), PHP_URL_PATH );
		$request_uri_path = parse_url( $_SERVER['REQUEST_URI'], PHP_URL_PATH );
		if (substr($request_uri_path, 0, strlen($home_url_path)) == $home_url_path) {
			$request_uri_path = substr($request_uri_path, strlen($home_url_path));
		}
		$base_request_uri = rawurlencode( get_home_url( null, $request_uri_path ) );

and then i use http://oauth.googlecode.com/svn/code/javascript/example/signature.html

but the end still show signature not match, any idea why?

**Comment by romuloctba** [comment]
I believe I got as far as you.. Will try again soon, since it was long ago... I guess we are supose to PR the way out of this

**Comment by wesleyxiao** [comment]
ok i just figure something out, may solve the problem, wait for my news, so exciting......^^

**Comment by romuloctba** [comment]
@wesleyxiao hope you discovered something nice

**Comment by LudovicFauchet** [comment]
Hello,

@romuloctba "oops, sorry.. you can download it here: http://rcdev.com.br/palestraexemplos/create-key.rar"

Your link is broken ? Can i have a good one ?

Cheers

**Comment by romuloctba** [comment]
@LudovicFauchet  if not yet too late https://gist.github.com/romuloctba/b973ff6bf87452e72f83

**Comment by younes0** [comment]
storing key/secret as a post meta... seriously

**Comment by rmccue** [comment]
@younes0 Thanks for your input, but this is not constructive. If you have thoughts on things we should do differently, please file an issue with constructive comments.

**Comment by younes0** [comment]
@rmccue my apologizes, but there's a lot of odd habits in the wordpress developers community, including how they handle data storing, sometimes in way that makes difficult database versioning and querying. And I'm not even talking about how they ignore the PHP Community (Composer packages, PSR).

Why would you store tokens in the post table ? Currently difficult to manage tokens. 
Wwhy not creating a new table for these ? It should be much more flexible, for instance if you need to store the API usage per token  (to rate limit)

**Comment by rmccue** [comment]
@younes0 Consumers are stored as post data in the backend, so it's natural to store this data as post meta. While we could create a custom table, there's a couple of good reasons we don't:

* The data fits pretty easily. Consumers have a name (`post_title`), a description (`post_content`), potentially an image (featured images), and potentially other custom data too.
* Posts automatically work with existing APIs, including post meta. This means it's pretty easy to add more data on as needed for extending it.
* This plugin is intended for WordPress core, and custom tables are very rarely added.

A better way to think about the structure is to think of posts as objects, and post meta as a key-value store for those objects. This generic object storage just happens to be unfortunately named "posts".

In your example with rate limiting, it's actually *easier* to achieve this with a key-value store, as you can simply add an extra property (post meta row) to the object. A custom table would require database migrations, along with the ability to reverse that migration (if you disable the plugin). This can also potentially lead to conflicts with multiple plugins that add columns, etc.

The only real issue here is that we're using a custom meta value to store the key, which is our primary key for finding the object. This makes lookups potentially expensive. That said, there is an index on `meta_key`, and the number of consumers is likely not too high on most sites as to be an issue.

**Comment by younes0** [comment]
@rmccue Thanks for the explanations! I should play more with the Wordpress API and not hitting directly the database.

**Comment by rmccue** [comment]
Admin UI is now available, and it displays the key and secret for you, as of #55 and #98. Sorry for the delay here folks!

**Comment by hatatouille** [comment]
dfdfdfdfdfdfdfdf
