### ISSUE TITLE
OAuth Signature does not match Swift OAuth Plugin

### ISSUE THREAD

**Issue by acoleman-apc** [WP-API/OAuth1#58]
Hello,

When trying to use the OAuthSwift framework: https://github.com/dongri/OAuthSwift

With this plug-in, the error "401 Unauthorized, response: OAuth signature does not match" is returned.

So one of the two is doing encoding differently.  Since the swift framework is working with other OAuth1 providers, I wonder if it isn't the wordpress plug-in?

Any guidance would be appreciated.

Thanks

**Comment by kosso** [comment]
Check the ordering of the OAuth parameters before they get concatenated etc.  Some OAuth libraries put them in alphabetical order before creating the signature. Took me quite a bit of debugging to figure this out. 

That could be it.

**Comment by jeremywho** [comment]
A lot of people seem to be getting this issue.  

I had this and it was because the URL I was using to call from the **client did not have the www** in the domain and OAuth was using a url with www. to calculate the signature.  I added www to the client and it started working.  Not sure if this is the case here, but just an FYI.

**Comment by acoleman-apc** [comment]
Using the latest version and making sure the Wordpress URL exactly matches in the client seems to have resolved the issue and so I am marking this issue as closed.  Thanks!
