### ISSUE TITLE
Won't work on internal multipress site

### ISSUE THREAD

**Issue by hefejeff** [WP-API/OAuth1#82]
I have been looking for a solution for this for days... This plugin works fine on a multisite network when posting to the main site but not to any of the sub sites.  I believe that a solution might be to force the rewrites to process the authentication request on the main site (captzapp.com) instead of the subsite (test.captzapp.com).  Is this something that might work?  Do you think I could just hard code this into the existing plugin.  

In the future maybe it could be handles with an if statement..?

**Comment by hefejeff** [comment]
I have now upgraded to WP REST API v2 and updated this plugin.  Has this been updated to authenticate calls to multisite subsites like test.captzapp.com?

**Comment by hefejeff** [comment]
I believe I have solved my issue and wanted to share.  I added the following code to class-wp-json-authentication-oauth1.php just below line 555 where the $base_request_uri is declared.

$array = explode(".", $base_request_uri);

    return (array_key_exists(count($array) - 2, $array) ? $array[count($array) - 2] : "").".".$array[count($array) - 1];

This strips the subdomain extension from the front of the URI forcing authentication via the main domain of the multisite installation.  

One question?  Do you think that this could jeopardize security in any way?

**Comment by coderkevin** [comment]
@hefejeff Was your issue that you were getting a "callback is invalid" error upon authentication?
I ran into this too because I was using localhost for development testing, so the call to wp_http_validate_url() was failing. If you look at the source for this function, there are several reasons for it to fail: https://developer.wordpress.org/reference/functions/wp_http_validate_url/
However, if it's just because it's seen as an "internal" site, you can fix this with a plugin filter hook. This is what I did for development, but you could make something more robust to check actual addresses:
``` php

/** TODO: Remove this. */
/** Temporary code to allow local external server for development */
function subvert_external_host_check( $allow, $host, $url ) {
  return true;
}
add_filter( 'http_request_host_is_external', 'subvert_external_host_check', 10, 3 );
```

**Comment by joehoyle** [comment]
Closing this out due to no reporter feedback in about a year, with solution suggested.
