### ISSUE TITLE
signature mismatch between `WP_Http::request()` and `WP_JSON_Authentication_OAuth1::create_signature_string()`

### ISSUE THREAD

**Issue by jtsternberg** [WP-API/OAuth1#93]
`WP_Http::request()` (which uses `http_build_query`) generates a POST body which is incompatible (in some instances) with `WP_JSON_Authentication_OAuth1::create_signature_string()` because `http_build_query` strips null values, so it creates a signature mismatch.

**Comment by rmccue** [comment]
I believe this is an issue on the request side with however you're generating the signature?

**Comment by JPry** [comment]
@rmccue 

> I believe this is an issue on the request side with however you're generating the signature?

In this particular case, we were using a process identical to the OAuth1 plugin to generate the signature. Here's the process:

1. Compile data array
2. Generate Oauth signature from data array
3. Use `wp_remote_post()` to send Oauth headers and data array as the request body.

In `wp_remote_post()`, the request body is converted from an array to a url-encoded string primarily using `http_build_query()`. The problem is that `http_build_query()` will remove null values. While this is indeed on the request side, the process used to generate the signature was copied exactly from the OAuth plugin, which is why this has been brought up here.

**Comment by jtsternberg** [comment]
@rmccue yes, you're right, it is a request-side issue, specifically the way `http_build_query` works. We built a workaround in our plugin: https://github.com/WebDevStudios/WDS-WP-REST-API-Connect/commit/11cbe606f26a333330e36a11af8adc7109c913eb

I'll close this issue. Thanks.
